### ISSUE TITLE
Proof for Additional Corollary 2.2.2

### ISSUE THREAD

**Issue by oiu850714** [ProFatXuanAll/terence-tao-analysis#1]
Hi, sorry I'm also not a native English speaker.
https://github.com/ProFatXuanAll/terence-tao-analysis/blob/master/Analysis-I/2-2-addition.tex#L71
https://github.com/ProFatXuanAll/terence-tao-analysis/blob/master/Analysis-I/2-2-addition.tex#L85
https://github.com/ProFatXuanAll/terence-tao-analysis/blob/master/Analysis-I/2-2-addition.tex#L100
It seems that the refs above should be 2.2.2, not 2.2.1.

Best regards.

**Comment by ProFatXuanAll** [comment]
FIxed.
Thanks.
