### ISSUE TITLE
Answer for Exercise 3.3.3

### ISSUE THREAD

**Issue by oiu850714** [ProFatXuanAll/terence-tao-analysis#2]
Hi,

https://github.com/ProFatXuanAll/terence-tao-analysis/blob/master/Analysis-I/3-3-functions.tex#L234-L245

I refer to [MSE](https://math.stackexchange.com/questions/3584055/when-is-the-empty-function-injective-surjective-bijective/3584072), it seems that empty function can be surjective if codomain is also the empty set?

**Comment by ProFatXuanAll** [comment]
[Fixed](https://github.com/ProFatXuanAll/terence-tao-analysis/commit/43b633a5e0cc5b8e6b567abb5b9f01419b1fd326).

Thanks.
